version: '3.8'
services:
  ilp:
    build: .
    container_name: gs-ILP_solver
    ports:
      - "8081:8081"  # Expose port 8081 for the web server
    restart: always   # Restarts if crashed or system rebooted
