TABLE_CAPACITY_ATTR = "capacity"
TABLE_HEAD_SEATS_ATTR = "head_seats"
TABLE_NEAR_FIELD_ATTR = "near_field"
TABLE_ID_ATTR = "table_id"

RESERVATION_NAME_ATTR = "name"
RESERVATION_SHOW_NAME_ATTR = "show_name"
RESERVATION_SIZE_ATTR = "size"
RESERVATION_REQUIRE_HEAD_ATTR = "required_head"
RESERVATION_NEAR_FIELD_ATTR = "near_field"
RESERVATION_CLOSE_TO_ATTR = "close_to"

AGGREGATE_RESERVATIONS_SUB_LIST_ATTR = "aggregated_reservations"
